services:
  - type: web
    name: airoom-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -w 4 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false
      - key: MONGODB_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: REDIS_URL
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: API_V1_PREFIX
        value: /api/v1
      - key: PROJECT_NAME
        value: AI Room Collaborator
      - key: VERSION
        value: 1.0.0

  - type: redis
    name: airoom-redis
    plan: free
    ipAllowList: [] 